#!/bin/bash

# ProActive wrapper for COSACS module.

# Functions
control_c(){
  echo Signal sent from Scheduler...
  COSACS_PID=`ps -ef | grep cosacs.xml | grep -v grep | tee log_cosacs_found.txt  | awk {'print $2'} | sort -n | head -1`
  # Check if COSACS_PID exists. 
  if [ "x$COSACS_PID" = "x" ]; then 
    echo Signal: no COSACS running... 
  else
    kill $COSACS_PID
  fi
  rm -f /home/cosacs/lock-`hostname`
}

CURRDIR=`dirname $0`

# Trapping the signals
trap control_c SIGINT
trap control_c SIGTERM

touch /home/cosacs/lock-`hostname`

/home/cosacs/run-cosacs &

COSACS_PID=`ps -ef | grep cosacs.xml | grep -v grep | tee log_cosacs_found.txt  | awk {'print $2'} | sort -n | head -1`

echo COSACS_PID is $COSACS_PID

# Check if COSACS_PID exists. 
if [ "x$COSACS_PID" = "x" ]; then 
#if [ -z "${COSACS_PID+xxx}" ]; then 
echo No COSACS running... Exiting...
rm -f /home/cosacs/lock-`hostname`
exit 0;
fi

echo $COSACS_PID > /home/cosacs/lock-`hostname`

echo Waiting for COSACS to be killed to remove the lock file... 
strace -p $COSACS_PID 

echo COSACS was killed, removing lock file...
rm -f /home/cosacs/lock-`hostname`

