#!/bin/bash
# ProActive wrapper for COSACS module.
CURRDIR=`dirname $0`
# Needs to be added the mechanism of lock-file (containing the PID of COSACS when running).

touch $CURRDIR/lock

$CURRDIR/run-cosacs &

COSACS_PID=`ps -ef | grep cosacs.xml | grep -v grep | tee log_cosacs_found.txt  | awk {'print $2'} | sort -n | head -1`

echo COSACS_PID is $COSACS_PID

# Check if COSACS_PID exists. 
if [ "x$COSACS_PID" = "x" ]; then 
#if [ -z "${COSACS_PID+xxx}" ]; then 
echo No COSACS running... Exiting...
exit 0;
fi

echo $COSACS_PID > $CURRDIR/lock

echo Waiting for COSACS to be killed to remove the lock file... 
strace -p $COSACS_PID 

echo COSACS was killed, removing lock file...
rm -f $CURRDIR/lock

