.TH CO-BROKER "7" "October 2012" "CompatibleOne" "Platform"
.SH NAME
co-broker \- This script allows the resources described by a plan to be provisioned as a service and started.
.SH SYNOPSIS
\fBco-broker\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This script allows the resources described by a plan to be provisioned as a service and started.
The script takes a single parameter, the stub name of the xml plan file without the xml file 
extension. The script launchs the executable bin/testcb and defines the required publisher 
and security information as described during installation.
.PP
\fBMandatory arguments\fR
.TP
\fBplatform\fR
Stub name of the XML manifest.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, written by Iain James Marshall.
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
