.TH CO-PARSER "7" "October 2012" "CompatibleOne" "Platform"
.SH SYNOPSIS
\fBco-parser\fR platform
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This script allows a manifest to be submitted for parsing and results in the creation
of a fully qualified plan. The script takes a single parameter, the stub name of the xml
manifest file without the xml file extension. The script launchs the executable bin/testcp
and defines the required publisher and security information as described during installation.
.PP
\fBMandatory arguments\fR
.TP
\fBplatform\fR
Stub name of the XML manifest.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, wrote by Iain James Marshall.
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
