.TH CO-STATUS "7" "October 2012" "CompatibleOne" "Platform"
.SH NAME
co\-status \- Get the status of the Accords platform.
.SH SYNOPSIS
\fBco-status\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This script may be launched to inspect the status of the Accords Platform. The status inspection 
operation may be performed by hand using either the ps command and grepping for the processes 
which use the the accords.xml configuration file. It may also be performed using netstat to detect
the individual server's listening socket.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, written by Iain James Marshall.
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
