.TH CO-STOP "7" "October 2012" "CompatibleOne" "Platform"
.SH SYNOPSIS
\fBco-stop\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This script must be launched to stop the Accords Platform and bring the servers offline.
This script takes no command line parameter and will perform a killall -15 operation for
each of the service components of the accords platform. Service components intercept this
signal and perform a garceful exit after releasing all ressources and saving any data.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, wrote by Iain James Marshall.
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
