.TH CO-START "7" "October 2012" "CompatibleOne" "Platform"
.SH NAME
co\-start \- Starts the Accords Platform and bring the services online.
.SH SYNOPSIS
\fBco-start\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This script must be launched to start the Accords Platform and bring the services online and 
takes no command line parameters. The script launchs the collection of run scripts, one for
each of the accords platform component servers. Each server will be launched in background
operation mode as a daemon process.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, written by Iain James Marshall.
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
