.TH COMPATIBLEONE "7" "October 2012" "CompatibleOne" "Project Description"
.SH SYNOPSIS
.PP
CompatibleOne is an open cloub broker platform.
.SH DESCRIPTION
.\" Add any additional description here
.PP
Goal of this project is to assist in deploying your stack cloud, the way you want,
using the providers you want for each component.
.PP
The CompatibleOne platform brokering is implemented in the current ACCORDS software.
.SS SEE ALSO
.TP
Have a look at the \fBaccords\fR(7) man page to learn more
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Written by Alexandre Lissy <alissy@mandriva.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
