.TH COSACS "7" "October 2012" "CompatibleOne" "Platform"
.SH NAME
cosacs-client \- CompatibleOne COSACS Client
.SH SYNOPSIS
\fBcosacs-client\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This will run the COSACS client from the CompatibleOne framework.
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, written by Iain James Marshall.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2012 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
