.TH STRUKT "7" "June 2013" "CompatibleOne" "Platform"
.SH NAME
strukt \- CompatibleOne Structure Constructor
.SH SYNOPSIS
\fBstrukt\fR
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
This tool allows to create structures to generate code for the CompatibleOne Accords plateform.
.SH OPTIONS
.TP
\fB\--verbose\fR
active verbose messages
.TP
\fB\--debug\fR
activate debug messages 
.TP
\fB\--echo\fR
echo source during input  
.TP
\fB\--xml\fR
generate xml production   
.TP
\fB\--occi\fR
generate occi production  
.TP
\fB\--mysql\fR
generate for mysql engine 
.TP
\fB\--crud\fR
generate crud actions     
.TP
\fB\--schema\fR
generate cords schema     
.TP
\fB\--cords <1:k|2:l|3:a|4:m>\fR
cords entity object type  
.SH AUTHOR
The CompatibleOne project.
.SH MANPAGE
Most of this documents comes from the README of ACCORDS, written by Iain James Marshall.
Written by Vincent Renardias <vrenardias@citypassenger.com> for the CompatibleOne project.
.SH "REPORTING BUGS"
Report CompatibleOne bugs to compatibleone@ow2.org
.br
CompatibleOne home page: <http://www.compatibleone.org>
.SH COPYRIGHT
Copyright \(co 2013 CompatibleOne.
License Apache 2.0.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
