#!/bin/bash
CURRDIR=`dirname $0`
echo Executing... 

DST_CONF=/var/lib/accords/paprocci
echo Copying configuration files to $DST_CONF...
mkdir -p $DST_CONF
rm -f $DST_CONF/*
cp $CURRDIR/conf/* $DST_CONF

DST_JARS=/usr/share/java/accords/paprocci
echo Copying .jar libraries to $DST_JARSs... 
mkdir -p $DST_JARS
rm -f $DST_JARS/*
cp $CURRDIR/java/lib/* $DST_JARS
cp $CURRDIR/java/dist/* $DST_JARS
