#!/bin/bash
CURRDIR=`dirname $0`
echo Executing... 
echo Note that this script needs to be set up with the correct JDK path. 
export JDK=/home/cone/bin/jdk1.6.0_25
export LD_LIBRARY_PATH=$JDK/jre/lib/i386/client:$JDK/jre/lib/i386
cd $CURRDIR/
echo $CURRDIR/src/paprocci --config $CURRDIR/../scripts/accords.xml CO-PAPROCCI/1.0
mkdir -p $CURRDIR/rest
$CURRDIR/src/paprocci --config $CURRDIR/../scripts/accords.xml CO-PAPROCCI/1.0


