Document: accords-platform
Title: Debian accords-platform Manual
Author: <insert document author here>
Abstract: This manual describes what accords-platform is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/accords-platform/accords-platform.sgml.gz

Format: postscript
Files: /usr/share/doc/accords-platform/accords-platform.ps.gz

Format: text
Files: /usr/share/doc/accords-platform/accords-platform.text.gz

Format: HTML
Index: /usr/share/doc/accords-platform/html/index.html
Files: /usr/share/doc/accords-platform/html/*.html
