#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "triggered" ] || [ "$1" = "upgrade" ] ; then

	if [ ! -e /var/lib/accords/accords.xml ] ; then
		cd /var/lib/accords/ && accords-config
	fi
fi

if [ -x /etc/init.d/compatibleone ]; then
	update-rc.d compatibleone defaults > /dev/null
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d compatibleone start
	else
		/etc/init.d/compatibleone start
	fi
fi

