#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "triggered" ] || [ "$1" = "upgrade" ] ; then

	if [ ! -e /var/lib/cosacs/config-cosacs.xml ] ; then
		echo "Should generate /var/lib/cosacs/config-cosacs.xml"
	fi
fi

if [ -x /etc/init.d/cosacs ]; then
	update-rc.d cosacs defaults > /dev/null
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d cosacs start
	else
		/etc/init.d/cosacs start
	fi
fi

