/*-------------------------------------------------------------------------------*/
/* Accords Platform                                                              */
/* copyright 2012 ,Hamid MEDJAHE (hmedjahed@prologue.fr)    Prologue             */
/*-------------------------------------------------------------------------------*/
/* Licensed under the Apache License, Version 2.0 (the "License");               */
/* you may not use this file except in compliance with the License.              */
/* You may obtain a copy of the License at                                       */
/*                                                                               */
/*       http://www.apache.org/licenses/LICENSE-2.0                              */
/*                                                                               */
/* Unless required by applicable law or agreed to in writing, software           */
/* distributed under the License is distributed on an "AS IS" BASIS,             */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      */
/* See the License for the specific language governing permissions and           */
/* limitations under the License.                                                */
/*-------------------------------------------------------------------------------*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JcompMgr */

#ifndef _Included_JcompMgr
#define _Included_JcompMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JcompMgr
 * Method:    generateCategory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_generateCategory
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     JcompMgr
 * Method:    removeCategory
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_removeCategory
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     JcompMgr
 * Method:    generateComponent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_generateComponent
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JcompMgr
 * Method:    removeComponent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_removeComponent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
