/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JcompMgr */

#ifndef _Included_JcompMgr
#define _Included_JcompMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JcompMgr
 * Method:    generateCategory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_generateCategory
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     JcompMgr
 * Method:    removeCategory
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_removeCategory
  (JNIEnv *, jobject, jstring,jint);

/*
 * Class:     JcompMgr
 * Method:    generateComponent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_generateComponent
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JcompMgr
 * Method:    removeComponent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JcompMgr_removeComponent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
